# Generated by Django 2.1.7 on 2019-07-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testJob',
            new_name='textJob',
        ),
    ]
