# Generated by Django 2.1.7 on 2019-03-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(max_length=200)),
                ('worker_ip', models.CharField(max_length=200)),
                ('last_ping', models.DateTimeField(verbose_name='last ping')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
